- name: win_powershell
  collections:
  - ansible.windows
  vars:
    ModulePath: C:\Program Files\PowerShell\7\Modules
  hosts: ws
  tasks:
    - name: Get-Version
      win_shell: |
        $version = pwsh -command 'Import-Module pSyslog; [string](Get-Module pSyslog | select Version)'
        $version = $version -replace "@{Version=|}"
        $tag  = (irm "https://api.github.com/repos/Lifailon/pSyslog/releases/latest").tag_name
        $hashtable = @{"Local" = "$version"; "GitHub" = "$tag"}
        $hashtable
      register: command_output
    - name: Command Output
      debug:
        var: command_output.stdout_lines
    - name: Deploy
      win_powershell:
        parameters:
          Module_Path: "{{ModulePath}}"
        script: |
          [CmdletBinding()]
          param (
            [String]$Module_Path
          )
          $Name_Module = "pSyslog"
          $Temp_Path = "$env:TEMP\$Name_Module.tar.gz"
          $GitHub_Rep = "https://api.github.com/repos/Lifailon/pSyslog/tarball"
          Invoke-WebRequest -URI $GitHub_Rep -outfile $Temp_Path # download
          Set-Location $env:TEMP
          tar -xzf $Temp_Path # extract gzip
          $Path_Arch = (Get-ChildItem *$Name_Module* -Directory).FullName
          Remove-Item "$Module_Path\$Name_Module" -Recurse -Force
          Copy-Item -Path "$Path_Arch\Module\pSyslog" -Destination "$Module_Path\" -Recurse
          Remove-Item $Temp_Path
          Remove-Item $Path_Arch -Recurse
          Get-ChildItem $Module_Path\$Name_Module | select FullName
      register: command_output
    - name: Command Output
      debug:
        var: command_output
    - name: Get-Version
      win_shell: |
        $version = pwsh -command 'Import-Module pSyslog; [string](Get-Module pSyslog | select Version)'
        $version = $version -replace "@{Version=|}"
        $tag  = (irm "https://api.github.com/repos/Lifailon/pSyslog/releases/latest").tag_name
        $hashtable = @{"Local" = "$version"; "GitHub" = "$tag"}
        $hashtable
      register: command_output
    - name: Command Output
      debug:
        var: command_output.stdout_lines