- name: win_powershell
  vars:
    ServiceName: winrm
  hosts: ws
  tasks:
    - name: Run PowerShell Commands
      ansible.windows.win_shell: |
        Get-Service *"{{ServiceName}}"*
      register: command_output
    - name: Command Output
      debug:
        var: command_output