- name: win_powershell
  vars:
    ServiceName: WinRM
    State: None
  hosts: ws
  tasks:
    - name: Get service state
      win_shell: |
        Get-Service *"{{ServiceName}}"* | Format-Table ServiceName,DisplayName,Status,StartType
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines
    - name: Change service state
      win_shell: |
        if ("{{State}}" -match "Start") {
          Get-Service *"{{ServiceName}}"* | Start-Service
        }
        elseif ("{{State}}" -match "Restart") {
          Get-Service *"{{ServiceName}}"* | Restart-Service
        }
        elseif ("{{State}}" -match "Stop") {
          Get-Service *"{{ServiceName}}"* | Stop-Service
        }
        else {
          Write-Host "No change in state"
        }
        if ("{{State}}" -match "Start|Restart|Stop") {    
          Get-Service *"{{ServiceName}}"* | Format-Table ServiceName,DisplayName,Status,StartType
        }
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines