- name: win_powershell
  vars:
    ServiceName: WinRM
    State: None
  hosts: ws
  tasks:
    - name: Run PowerShell Commands
      win_shell: |
        Get-Service *"{{ServiceName}}"*
        echo ""
        if ("{{State}}" -like "Start") {
          Start-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
        if ("{{State}}" -like "Restart") {
          Restart-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
        if ("{{State}}" -like "Stop") {
          Stop-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
      register: command_output
    - name: Command Output
      debug:
        var: command_output.stdout_lines