- name: win_powershell
  collections:
  - ansible.windows
  hosts: ws
  tasks:
    - name: Run PowerShell Commands
      win_shell: |
        $version = pwsh -command 'Import-Module pSyslog; [string](Get-Module pSyslog | select Version)'
        $version = $version -replace "@{Version=|}"
        $tag  = (irm "https://api.github.com/repos/Lifailon/pSyslog/releases/latest").tag_name
        $hashtable = @{"Local" = "$version"; "GitHub" = "$tag"}
        $hashtable
      register: command_output
    - name: Command Output
      debug:
        var: command_output.stdout_lines