- name: win_powershell
  vars:
    ServiceName: WinRM
    State: None
    StartType: None
    System: Windows
  hosts: ws
  tasks:
    - name: Get-Service
      win_shell: |
        if ("{{System}}" -eq "Windows") {
          $RegPath = "HKLM:\SOFTWARE\Microsoft\PowerShellCore\InstalledVersions\*"
          $PS7Ver = (Get-ItemProperty -Path $RegPath -ErrorAction Ignore).SemanticVersion
          if ($PS7Ver -ne $null) {
            Write-Host "PowerShell 7: True (version: $PS7Ver)"
          }
          else {
            Write-Host "PowerShell 7: False"
          }
          Get-Service *"{{ServiceName}}"* | Format-Table ServiceName,Status,StartType,DisplayName
          # pwsh -c 'Get-Service *"{{ServiceName}}"* | Format-Table ServiceName,Status,StartupType,DisplayName,BinaryPathName'
        }
        else {
          Write-Host "Linux operating system selected"
        }
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines
    - name: Change service state Windows
      win_shell: |
        if ("{{StartType}}" -match "Automatic|Disabled|Manual") {
          Get-Service *"{{ServiceName}}"* | Set-Service -StartMode "{{StartType}}"
          pwsh -c 'Get-Service *"{{ServiceName}}"* | Set-Service -StartMode "{{StartType}}"'          
        }
        if ("{{StartType}}" -like "AutomaticDelayedStart") {
          pwsh -c 'Get-Service *"{{ServiceName}}"* | Set-Service -StartMode "{{StartType}}"'
        }
        if ("{{State}}" -match "Start") {
          Get-Service *"{{ServiceName}}"* | Start-Service
        }
        elseif ("{{State}}" -match "Restart") {
          Get-Service *"{{ServiceName}}"* | Restart-Service
        }
        elseif ("{{State}}" -match "Stop") {
          Get-Service *"{{ServiceName}}"* | Stop-Service
        }
        else {
          Write-Host "No change in state"
        }
        if ( ("{{State}}" -notmatch "None") -or ("{{StartType}}" -notmatch "None") ) {    
          Get-Service *"{{ServiceName}}"* | Format-Table ServiceName,Status,StartType,DisplayName
        }
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines
    - name: Change service state Linux
      shell:
        echo "test"
        echo "test2"
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines