- name: win_powershell
  vars:
    ServiceName: WinRM
    State: None
    StartType: None
  hosts: ws
  tasks:
    - name: Get service state
      win_shell: |
        Get-Service *"{{ServiceName}}"* | Format-Table ServiceName,Status,StartType,DisplayName # StartupType,BinaryPathName,Description
        $RegPath = "HKLM:\SOFTWARE\Microsoft\PowerShellCore\InstalledVersions\*"
        (Get-ItemProperty -Path $RegPath).SemanticVersion
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines
    - name: Change service state
      win_shell: |
        if ("{{State}}" -match "Start") {
          Get-Service *"{{ServiceName}}"* | Start-Service
        }
        elseif ("{{State}}" -match "Restart") {
          Get-Service *"{{ServiceName}}"* | Restart-Service
        }
        elseif ("{{State}}" -match "Stop") {
          Get-Service *"{{ServiceName}}"* | Stop-Service
        }
        else {
          Write-Host "No change in state"
        }
        if ("{{StartType}}" -notmatch "None") {
          Get-Service *"{{ServiceName}}"* | Set-Service -StartupType "{{StartType}}"
          Get-Service *"{{ServiceName}}"* | Set-Service -StartType "{{StartType}}"
          Get-Service *"{{ServiceName}}"* | Set-Service -StartMode "{{StartType}}"
        }
        if ( ("{{State}}" -notmatch "None") -or ("{{StartType}}" -notmatch "None") ) {    
          Get-Service *"{{ServiceName}}"* | Format-Table ServiceName,Status,StartType,DisplayName
        }
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines