- name: win_powershell
  vars:
    ServiceName: WinRM
    State: None
  hosts: ws
  tasks:
    - name: Get service state
      win_shell: |
        Get-Service *"{{ServiceName}}"*
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines
    - name: Change service state
      win_shell: |
        if ("{{State}}" -like "Start") {
          Start-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
        elseif ("{{State}}" -like "Restart") {
          Restart-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
        elseif ("{{State}}" -like "Stop") {
          Stop-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
        else {
          Write-Host "No change in state"
        }
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines