- name: win_powershell
  hosts: ws
  tasks:
    - name: Run PowerShell Commands
      win_shell: |
        $PSVersionTable
        Import-Module pSyslog
        $version = [string](Get-Module pSyslog | select Version) -replace "@{Version=|}"
        $tag  = (irm "https://api.github.com/repos/Lifailon/pSyslog/releases/latest").tag_name
        $hashtable = @{"Local" = "$version"; "GitHub" = "$tag"}
        $hashtable
      register: command_output
    - name: Command Output
      debug:
        var: command_output.stdout_lines