- name: win_powershell
  vars:
    ServiceName: WinRM
    State: false
  hosts: ws
  tasks:
    - name: Run PowerShell Commands
      win_shell: |
        Get-Service *"{{ServiceName}}"*
        if ("{{State -match 'Start'}}") {
          Start-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
        elseif ("{{State -match 'Stop'}}") {
          Stop-Service *"{{ServiceName}}"*
          Get-Service *"{{ServiceName}}"*
        }
      register: command_output
    - name: Command Output
      debug:
        var: command_output.stdout_lines