- name: win_powershell
  vars:
    ServiceName: ssh
    State: None
    StartType: None
  hosts: us
  tasks:
    - name: Change service state Linux
      shell:
        systemctl status *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - ";
        echo выбрано "{{State}}";
        if [[ "{{State}}" == "Start" ]];
        then systemctl start "{{ServiceName}}"; echo условие start;
        elif [[ "{{State}}" == "Stop" ]];
        then systemctl stop "{{ServiceName}}"; echo условие stop;
        else echo условие none;
        fi;
        systemctl status *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines