- name: linux_shell
  vars:
    ServiceName: cron
    State: None
    StartType: None
  hosts: us
  tasks:
    - name: Get service state Linux
      shell: |
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output state service
      debug:
        var: command_output.stdout_lines
    - name: Start service
      when: State == "Start"
      shell: |
        systemctl start -a *"{{ServiceName}}"*
    - name: Stop service
      when: State == "Stop"
      shell: |
        systemctl stop -a *"{{ServiceName}}"*
    - name: Restart service
      when: State == "Restart"
      shell: |
        systemctl restart -a *"{{ServiceName}}"*
    - name: Enable service to startup
      when: StartType == "Enabled"
      shell: |
        systemctl enable -a "{{ServiceName}}"
    - name: Disable service to startup
      when: StartType == "Disabled"
      shell: |
        systemctl disable -a "{{ServiceName}}"
    - name: Get service state
      when: State != "None" and StartType == "None"
      shell: |
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output state service finish
      when: State != "None" and StartType == "None"
      debug:
        var: command_output.stdout_lines
    - name: Get service state
      when: StartType != "None"
      shell: |
        systemctl status -a "{{ServiceName}}" | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output state service finish
      when: StartType != "None"
      debug:
        var: command_output.stdout_lines