- name: linux_shell
  vars:
    ServiceName: cron
    State: None
    StartType: None
  hosts: us
  tasks:
    - name: Get service state Linux
      shell: |
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - ";
      register: command_output
    - name: Output state
      debug:
        var: command_output.stdout_lines
    - name: Start service
      when: State == "Start"
      shell: |
        systemctl start -a *"{{ServiceName}}"*;
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output start service
      when: State == "Start"
      debug:
        var: command_output.stdout_lines
    - name: Stop service
      when: State == "Stop"
      shell: |
        systemctl stop -a *"{{ServiceName}}"*;
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output stop service
      when: State == "Stop"
      debug:
        var: command_output.stdout_lines
    - name: Restart service
      when: State == "Restart"
      shell: |
        systemctl restart -a *"{{ServiceName}}"*;
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output restart service
      when: State == "Restart"
      debug:
        var: command_output.stdout_lines
    - name: Enable service to startup
      when: StartType == "Enabled"
      shell: |
        systemctl enable -a *"{{ServiceName}}"*;
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output ensable service
      when: StartType == "Enabled"
      debug:
        var: command_output.stdout_lines
    - name: Disable service to startup
      when: StartType == "Disabled"
      shell: |
        systemctl disable -a *"{{ServiceName}}"*;
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output disable service
      when: StartType == "Disabled"
      debug:
        var: command_output.stdout_lines