- name: linux_shell
  vars:
    ServiceName: cron
    State: None
    StartType: None
  hosts: us
  tasks:
    - name: Get service state
      shell: |
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - ";
        echo выбрано "{{State}}";
    - name: Change service state Linux
      when: State == "Stop"
      shell: |
        systemctl stop *"{{ServiceName}}"*; echo условие попало под stop;
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines