- name: win_powershell
  vars:
    ServiceName: WinRM
    State: None
    StartType: None
    System: Linux
  hosts: us
  tasks:
    - name: Change service state Linux
      shell:
        systemctl status cron
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines