- name: win_powershell
  vars:
    ServiceName: ssh
    State: None
    StartType: None
  hosts: us
  tasks:
    - name: Change service state Linux
      shell:
        systemctl status *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - ";
        if [[ "{{State}}" -eq "Start" ]];
        then systemctl start *"{{ServiceName}}"*;
        elif [[ "{{State}}" -eq "Stop" ]];
        then systemctl stop *"{{ServiceName}}"*;
        fi;
        systemctl status *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines