- name: linux_shell
  vars:
    ServiceName: cron
    State: None
    StartType: None
  hosts: us
  tasks:
    - name: Change service state Linux
      shell: |
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - ";
        echo выбрано "{{State}}";
        if [[ {{ State }} == Stop ]]; then echo DA DA DA; fi;
        if [[ "{{ State }}" -eq "Start" ]]; then systemctl start *"{{ServiceName}}"*; echo условие попало под start; fi;
        if [[ "{{ State }}" -eq "Stop" ]]; then systemctl stop *"{{ServiceName}}"*; echo условие попало под stop; fi;
        if [[ "{{ State }}" -eq "Restart" ]]; then systemctl restart *"{{ServiceName}}"*; echo условие попало под restart; fi;
        systemctl status -a *"{{ServiceName}}"* | grep -iP "Active:|Loaded:| - "
      register: command_output
    - name: Output
      debug:
        var: command_output.stdout_lines